# Generated by Django 3.0.6 on 2020-06-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_delete_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealer',
            options={'verbose_name': 'Dealer', 'verbose_name_plural': 'Dealers'},
        ),
    ]
