version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: django_backand
    command: "python manage.py runserver 0:8000"
    ports:
      - 8080:8080
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: ./deploy/conteiners/postgres.Dockerfile
    container_name: orm_example
    restart: always
    env_file:
      - ./deploy/envs/.env-local
    ports:
      - "5432:5432"
    volumes:
      - .data/postgres:/var/lib/postgresql/data/