version: '3.7'

services:
  web:
    build: ../practice/application
    ports:
      - 8000:5000

  db:
    image: postgres:latest
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cursor
      - POSTGRES_PASSWORD=very_secret_password
      - POSTGRES_DB=cursor_sqlalchemy_db

#volumes:
#  postgres_data: