"""Order_price

Revision ID: 4ab4dde7b25c
Revises: 714be770e872
Create Date: 2020-05-27 14:09:17.979050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab4dde7b25c'
down_revision = '714be770e872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_sum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_sum')
    # ### end Alembic commands ###
